services:
  web-server:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=catskillet
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  celery-worker:
    build: .
    depends_on:
      - redis
    command: ["uv", "run", "celery", "-A", "agenda", "worker", "--loglevel=info"]
