# Generated by Django 5.2.4 on 2025-07-25 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('icon', models.ImageField(upload_to='icons/')),
                ('created_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=400)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Task pending'), ('ONGOING', 'Task in progress'), ('DONE', 'Task done')])),
                ('created_on', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'title', 'date'), name='unique_task')],
            },
        ),
    ]
