# Generated by Django 5.2.4 on 2025-07-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_unique_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
